### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by linpogo** [abdullahfarwees/screen-recorder-ffmpeg-cpp#13]
Hi sir,
I run your program on ubuntu18.
It will appears the following message.
"./ScreenRecorder: error while loading shared libraries: libva.so.1: cannot opeshared object file: No such file or directory".
I google how to install this sharre libraries. 
>sudo apt install libva1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libva1

I can't install libva1.
Could you help me to solve this problem?

**Comment by abdullahfarwees** [comment]
sudo apt update
sudo apt install libva-dev

This might help you!.
