### ISSUE TITLE
Is there away to set output to be a udp stream

### ISSUE THREAD

**Issue by FXUDarkNova** [abdullahfarwees/screen-recorder-ffmpeg-cpp#2]
I am new to ffmpeg c++ is there a way to set the output to be a udp stream so I can capture my desktop on another device?

**Comment by abdullahfarwees** [comment]
Yes, instead of writing into the file, redirect to UDP url. click the following links for reference. 

https://github.com/leixiaohua1020/simplest_ffmpeg_streamer/blob/master/simplest_ffmpeg_streamer/simplest_ffmpeg_streamer.cpp

Also,Do not forget to refer here libavformat/udp.c in the source.
